# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  foo: 'beef'
  bar: $[replace(variables['foo'], 'beef', 'steak')]

pool:
  vmImage: ubuntu-latest



steps:
- script: echo This should be steak but it is $(bar)
- bash: |
   git clone git@ssh.dev.azure.com:v3/paidpiper2020/PaidPiper/test 
   mv newfile1 newfile2
  displayName: 'rename file'

- bash: |
   git push --prune https://$(GITHUB_PAT)@github.com/$REPO_NAME \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Github'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')