# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
      Write-Host ' reflect Azure Devops repo changes to GitHub repo'
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '$stageDir = '$(Build.SourcesDirectory)' | Split-Path
      $githubDir = $stageDir +"\"+"gitHub"
      $destination = $githubDir +"\"+"test.git"#please provide your username
      $alias = 'scsi-9:'+ "$(Github.PAT)"#Please make sure, you remove https from azure-repo-clone-url
      $sourceURL = 'https://$(AzureDevOps.PAT)@paidpiper2020@dev.azure.com/paidpiper2020/PaidPiper/_git/test'#Please make sure, you remove https from github-repo-clone-url
      $destURL = 'https://' + $alias + '@github.com/SCSI-9/test.git'#Check if the parent directory exists and delete
      if((Test-Path -path $githubDir))
      {
        Remove-Item -Path $githubDir -Recurse -force
      }if(!(Test-Path -path $githubDir))
      {
        New-Item -ItemType directory -Path $githubDir
        Set-Location $githubDir
        git clone --mirror $sourceURL
      }
      else
      {
        Write-Host "The given folder path $githubDir already exists";
      }Set-Location $destinationWrite-Output '*****Git removing remote secondary****'
      git remote rm secondaryWrite-Output '*****Git remote add****'
      git remote add --mirror=fetch secondary $destURLWrite-Output '*****Git fetch origin****'
      git fetch $sourceURLWrite-Output '*****Git push secondary****'
      git push secondary --allWrite-Output '**Azure Devops repo synced with Github repo**'
      Set-Location $stageDirif((Test-Path -path $githubDir))
      {
       Remove-Item -Path $githubDir -Recurse -force
      }
