# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  DESTIONATION_URL: 'git@github.com:SCSI-9/test.git'
  SOURCE_URL: 'git@ssh.dev.azure.com:v3/paidpiper2020/PaidPiper'

pool:
  vmImage: ubuntu-20.04

steps:
- bash: |
   find . -type f -name ".gitmodules" -print0 | xargs -0 sed -i  's+git@ssh.dev.azure.com:v3/paidpiper2020/PaidPiper+git@github.com:SCSI-9/test.git+g'
   awk '{print $0":.git"}1' ./.gitmodules
   cat .gitmodules
   git config --global user.email "example@hotmail.com"
   git config --global user.name "example"
   git add .
   git commit -m "change gitmodules"
   git config pull.rebase true
   git pull https://$(GITHUB_PAT)@github.com/$REPO_NAME
   git push https://$(GITHUB_PAT)@github.com/$REPO_NAME   HEAD:main
   git show-ref
  displayName: 'fix links git GitHub'