# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  SOURCE_URL: 'git@ssh.dev.azure.com:v3/paidpiper2020/PaidPiper'
  DESTIONATION_URL: $[replace(variables['DESTIONATION_URL'], 'git@ssh.dev.azure.com:v3/paidpiper2020/PaidPiper', 'git@github.com:SCSI-9/test.git')]

pool:
  vmImage: ubuntu-20.04

steps:
- bash: |
   find . -type f -name ".gitmodules" -print0 | xargs -0 sed -i 's+git@ssh.dev.azure.com:v3/paidpiper2020/PaidPiper+git@github.com:SCSI-9/test.git+g'
   cat .gitmodules
   git config --global user.email "adil.hasanov@hotmail.com"
   git config --global user.name "scsi-9"
   git pull https://$(GITHUB_PAT)@github.com/$REPO_NAME --rebase origin main
   git add .
   git commit -m "change gitmodules"
   git push https://$(GITHUB_PAT)@github.com/$REPO_NAME origin HEAD:main
   git show-ref
  displayName: 'fix links git GitHub'